from model.coffee import CoffeeModel
model = CoffeeModel('CoffeeRatings.csv')
model.visualize()
model.clean()
model.standarize()
print("SVM LINEAL")
model.svm_lineal(cost_parameter=1)
print("SVM GAUSSIANO")
model.svm_gaussiano()
print("RANDOM FOREST")
model.random_forest()
